### ISSUE TITLE
Add workaround for corrupted nsys GPU utilization data

### ISSUE THREAD

**Issue by GregoryKimball** [NVIDIA/nvbench#104]
libcudf benchmarks run using nvbench show a conflict with Nsight Systems when collecting GPU utilization data. This issue is tracked in the Nsight Systems Jira board ([Slack thread](https://nvidia.slack.com/archives/C0ENDAPP1/p1662581506457839?thread_ts=1662581269.587039&cid=C0ENDAPP1), [Jira Issue](https://jirasw.nvidia.com/browse/DTSP-13459)).

The current consensus is that the root cause lies within Nsight Systems collects utilization data. I'm opening this issue to request that nvbench investigates a workaround. C++ google benchmarks and python pytest benchmarks have no issues collecting GPU utilization data with Nsight Systems, so there must be some way for nvbench user using the `--profile` flag to access GPU utilization data.

Reference profile with nvbench:
![image](https://user-images.githubusercontent.com/12725111/201160605-106b4622-acdd-48f5-883b-61ecd5fdc2f1.png)

Reference profile with gbench:
![image](https://user-images.githubusercontent.com/12725111/201160809-48b389e7-66e4-4fdd-8254-2db8d118463d.png)

**Comment by bdice** [comment]
The corresponding [JIRA issue](https://jirasw.nvidia.com/browse/DTSP-13459) has been closed. @GregoryKimball Can this be closed?

**Comment by GregoryKimball** [comment]
Thank you @bdice for checking in. I'm sorry to say that there is a still a problem here at the intersection of `nsys` and `nvbench`.

When running this command on RAPIDS devel image `9ddc9c4c2046`
```
B=JOIN_NVBENCH && /nfs/nsight-systems-2022.5.1/bin/nsys profile -t nvtx,cuda,osrt -f true --cuda-memory-usage=true --gpu-metrics-device=0 --output=/nfs/20230113_mixed_join/"$B" cpp/build/benchmarks/"$B" --devices 0 --profile --json /nfs/20230113_mixed_join/"$B".json | tee /nfs/20230113_mixed_join/"$B".txt
```

We receive this nsys diagnostics error instead of valid GPU Utilization metrics:
```
Error when processing events: Source ID=
Type=ErrorInformation (18)
 Error information:
 ProcessEventsError (4005)
  Properties:
  ErrorText (100)=/dvs/p4/build/sw/devtools/Agora/Rel/QuadD_Main/QuadD/Host/Analysis/EventHandler/GpuMetricsEventHandler.cpp(202): Throw in function void QuadDAnalysis::EventHandler::GpuMetricsEventHandler::PutEvent(QuadDAnalysis::EventHandler::GpuMetricsEventHandler::EventPtr)
Dynamic exception type: boost::wrapexcept
std::exception::what: ChronologicalOrderError
[QuadDCommon::tag_message*] = GPU Metrics event chronological order was broken.
```

The error only occurs with `nvbench`, and never with google benchmarks or pytest, so I still think we need an option in `nvbench` to workaround corrupted GPU utilization data. I am hoping that the workaround would take the form of a "cuda safe mode" that makes `nvbench` act like a GPU-naive benchmarking tool.

**Comment by GregoryKimball** [comment]
Closed by https://github.com/rapidsai/cudf/pull/12728
