### ISSUE TITLE
Is there anyway to build offline?

### ISSUE THREAD

**Issue by ax7e** [NVIDIA/nvbench#112]
I was trying to use nvbench in private network, where I can not reach github.
Is there any settings or way so that I can build this project offline?

**Comment by miscco** [comment]
You can always fork the project and put it somewhere reachable. 

That would still require you to occasionally sync with main, but that would be a rather rare thing

**Comment by senior-zero** [comment]
@miscco the problem with cloning is that nvbench cmake files are fetching rapids cmake from github. Even if you prefetch some files before configuring cmake, I'm not sure that it'll work as expected. Rapids cmake is cloning other sub projects from github. @allisonvacanti is there a workaround for that?

**Comment by miscco** [comment]
I fear then the most probable solution is to clone all dependencies and adopt the cmake files to point to the internal repositories

**Comment by ax7e** [comment]
Well in my situation, the server are completely offline, but the rapids-cmake requires to connect to github for version checking. Even if I set CPM_CACHE(sorry I forget the concrete name), the rapids-cmake still needs to connect to github.

**Comment by ax7e** [comment]
> I fear then the most probable solution is to clone all dependencies and adopt the cmake files to point to the internal repositories

I have tried to set CPM_USE_LOCAL and changed the links inside rapid_find_packages to point to local paths, but this is not working as well. If anyone is interested, I can make it public. I think the best way is to completely rewrite the cmakefiles to create another version that uses git submodule rather than rapids.

**Comment by allisonvacanti** [comment]
Has this been resolved?

**Comment by ax7e** [comment]
@robertmaynard Thanks, your solution worked in my environment.
