### ISSUE TITLE
CUDA version requirement

### ISSUE THREAD

**Issue by yukarinoki** [NVIDIA/nvbench#18]
This repo can't be compiled by CUDA 11.0 (and older).
In my environment (CUDA 11.0), a compile error(below) happened at `json_print.o`.
```
[  3%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/format.cc.o
[  6%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[ 10%] Linking CXX static library libfmt.a
[ 10%] Built target fmt
Scanning dependencies of target nvbench
[ 13%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/axes_metadata.cu.o
[ 16%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/axis_base.cu.o
[ 20%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/benchmark_base.cu.o
[ 23%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/benchmark_manager.cu.o
[ 26%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/blocking_kernel.cu.o
[ 30%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/csv_printer.cu.o
[ 33%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/cuda_call.cu.o
[ 36%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/device_info.cu.o
[ 40%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/device_manager.cu.o
[ 43%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/float64_axis.cu.o
[ 46%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/int64_axis.cu.o
[ 50%] Building CUDA object nvbench/CMakeFiles/nvbench.dir/json_printer.cu.o
Segmentation fault (core dumped)
make[2]: *** [nvbench/CMakeFiles/nvbench.dir/build.make:225: nvbench/CMakeFiles/nvbench.dir/json_printer.cu.o] Error 139
make[1]: *** [CMakeFiles/Makefile2:220: nvbench/CMakeFiles/nvbench.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```
I think the reason for this error is that the backend gcc compiler of CUDA 11.0 doesn't fully support C++17 (I am not sure). Actually, I could compile by CUDA 11.2.

The bad thing about this error is that it gives no information to the user. In fact, it took me some time to identify the cause.
So, could you either make it clear in the documentation that CUDA 11.2 or higher is required, or put a condition on the version of CUDA by cmake. (I think the latter would be more user-friendly.)

**Comment by jrhemstad** [comment]
CUDA 11 should fully support C++17 and should be the minimum required CUDA version.

I suspect there may just be a compiler bug in nvcc 11.0.

**Comment by allisonvacanti** [comment]
For now it's probably best to just stick with 11.1+. @jrhemstad is right, this is due to a compiler bug in 11.0 that has since been fixed.

@robertmaynard discovered that commenting out this function in `json.hpp` (from our `nlohmann/json` dependency) will work-around the issue on 11.0:

```
// JSON_HEDLEY_NON_NULL(1)
// inline nlohmann::json operator "" _json(const char* s, std::size_t n)
// {
//     return nlohmann::json::parse(s, s + n);
// }
```

We could also patch this as part of our CPM checkout, but it may be some time until I get to this.

**Comment by jrhemstad** [comment]
> We could also patch this as part of our CPM checkout, but it may be some time until I get to this.

Perhaps someone on the RAPIDS team could take this on as we have to support 11.0 for a while and this would block us from using nvbench.

**Comment by robertmaynard** [comment]
I can take this on
