### ISSUE TITLE
Add `--profile` flag to fixup various profiling issues

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/nvbench#45]
#10 was a similar issue about adding support for profiling -- this issue resulted in the `--run-once` option, which disables warmup runs and only does a single execution of the `KernelLauncher`.

However, there is another issue when using CUDA profilers. The profiler will force the CPU to block until the kernel is executed, and this causes a deadlock when a benchmark uses the `blocking_kernel`. This can be worked around by using `nvbench::exec_tag::sync` to disable the blocking kernel, but we should add a runtime switch to disable this as well.

- [ ] Add `--disable-blocking-kernel` to simply switch off the blocking kernel
- [ ] Add `--profile`, which implies `--disable-blocking-kernel --run-once`

**Comment by jrhemstad** [comment]
Likewise, I believe using CUPTI as in https://github.com/NVIDIA/nvbench/pull/29 would break Nsight Systems. When that PR is merged, `--profile` should probably disable anything using CUPTI as well.

**Comment by allisonvacanti** [comment]
Good catch, thanks for pointing that out.

CUPTI will already be disabled when the `run_once` flag is enabled, so this should be taken care of automatically.
