### ISSUE TITLE
[FEA] Built-in bandwidth measurement via CUPTI

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/nvbench#5]
Does it make sense to introduce profiling tools like CUPTI into nvbench?

In that way, nvbench can provide precise bandwidth measurement by using CUPTI metrics like `gld_throughput` and `gst_throughput`.

Instead of manually specifying data type and size:
```
state.add_global_memory_reads<InputType>(size);
state.add_global_memory_writes<OutputType>(size);
```
Users may simply use `NVBENCH_BENCH(bm).add_global_memory_bandwidth();` to add such measurement into their tests.

**Comment by allisonvacanti** [comment]
This is definitely something I want to have at some point. The current plan is to eventually add both CUPTI and NVML as optional dependencies and use them to implement these sorts of conveniences.

**Comment by PointKernel** [comment]
> This is definitely something I want to have at some point. The current plan is to eventually add both CUPTI and NVML as optional dependencies and use them to implement these sorts of conveniences.

That will be great!
