### ISSUE TITLE
Add JSON output format options

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/nvbench#51]
It'd be nice to support a JSON benchmark output format a la [Google Bench](https://github.com/google/benchmark/blob/main/docs/user_guide.md#output-formats). This would make scripted perf tracking for nvbench runs much simpler.

**Comment by allisonvacanti** [comment]
Did you try `--json <filename>`? ([Output Formats](https://github.com/NVIDIA/nvbench/blob/main/docs/cli_help.md#output))

**Comment by randerzander** [comment]
No, but now I did and it works 😊 

Thanks!
