### ISSUE TITLE
Unused parameter warnings

### ISSUE THREAD

**Issue by harrism** [NVIDIA/nvbench#75]
The following two lines cause unused parameter warnings when `NVBENCH_HAS_NVML` is false.

https://github.com/NVIDIA/nvbench/blob/b1b6d73afac528ccbe4e3300190c0dba419feb36/nvbench/device_info.cu#L59
https://github.com/NVIDIA/nvbench/blob/b1b6d73afac528ccbe4e3300190c0dba419feb36/nvbench/device_info.cu#L91

**Comment by allisonvacanti** [comment]
This was fixed in #69.
