### ISSUE TITLE
[QST] Is there any way to pass filenames to nvbench via command line?

### ISSUE THREAD

**Issue by annielytical** [NVIDIA/nvbench#86]
All of the examples I'm seeing use synthetic datasets, which are not useful for us. 

Thanks!

**Comment by allisonvacanti** [comment]
You'll need to implement your own `main(argc, argv)` function to parse out additional arguments, and then use the macros defined in [main.cuh](https://github.com/NVIDIA/nvbench/blob/main/nvbench/main.cuh) to parse the remaining args and run NVBench. Something like:

```
int main(int argc, char** argv)
{
  // parse custom args and remove them from (or rebuild) argc/argv here
  
  NVBENCH_MAIN_BODY(argc, argv);
}
```

You'll need a singleton or some global state to make the filename available to the benchmarks.

We should add an example that does this.

**Comment by annielytical** [comment]
Very helpful. Thank you!

**Comment by allisonvacanti** [comment]
No problem! I'm not sure anyone has tried doing this before, so please reach out if you encounter any issues. I've opened #87 to track adding an example.
